{% set name = "mockafka-py" %}
{% set version = "0.1.61" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mockafka_py-{{ version }}.tar.gz
  sha256: cd3c8320f2e7552cbf1641a6da0bb1124f5388789e2408b2e99d978cfcc61fda

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }},<4.0
    - python-confluent-kafka >=1.9.2
    - aiokafka >=0.10.0,<0.11.0
    - pytest-cov >=4.1,<6.0
    - pytest-asyncio >=0.23.5,<0.24.0
    - parameterized >=0.9.0,<0.10.0

test:
  imports:
    - mockafka
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/alm0ra/mockafka-py
  summary: A mock library for confluent kafka
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apmorton
